name: Clear Workspace
description: Clear workspace on github actions self-hosted runner
runs:
  using: "composite"
  steps:
    - shell: bash 
      run: |
        sudo rm -rf ${{ github.workspace }}
        mkdir -p ${{ github.workspace }}
      
