name: Clear Workspace
description: This action clears the github workspace for the currently running workflow. This is designed to be used on self-hosted runners where the project workspace persists between workflow runs. Many times cleaning the workspace is essential to success.
runs:
  using: "composite"
  steps:
    - shell: bash 
      run: |
        echo "Cleaning workspace directory..."
        sudo rm -rfv ${{ github.workspace }}
        mkdir -p ${{ github.workspace }}
      
